# Generated by Django 6.0.4 on 2026-05-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('level', models.CharField(choices=[('university', 'Universitet'), ('faculty', 'Fakultet'), ('department', 'Kafedra'), ('group', 'Guruh'), ('personal', 'Shaxsiy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "O'qilgan xabarnoma",
                'verbose_name_plural': "O'qilgan xabarnomalar",
            },
        ),
    ]
