# Generated by Django 4.2.13 on 2026-05-11 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0002_initial'),
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(to='academic.subject')),
            ],
            options={
                'verbose_name': 'Fan tanlovi',
                'verbose_name_plural': 'Fan tanlovlari',
            },
        ),
        migrations.CreateModel(
            name='SubjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Fan resursi',
                'verbose_name_plural': 'Fanlar resurslari',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('mon', 'Dushanba'), ('tue', 'Seshanba'), ('wed', 'Chorshanba'), ('thu', 'Payshanba'), ('fri', 'Juma'), ('sat', 'Shanba')], max_length=3)),
                ('pair_number', models.PositiveSmallIntegerField()),
                ('room', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='university.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
            },
        ),
        migrations.CreateModel(
            name='RetakeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
            options={
                'verbose_name': "Qayta o'qish arizasi",
                'verbose_name_plural': "Qayta o'qish arizalari",
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('exam_type', models.CharField(choices=[('oraliq', 'Oraliq'), ('yakuniy', 'Yakuniy')], max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
            options={
                'verbose_name': 'Nazorat jadvali',
                'verbose_name_plural': 'Nazorat jadvallari',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('total_hours', models.PositiveIntegerField(default=30)),
                ('credit_points', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='university.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
            options={
                'verbose_name': "O'quv reja",
                'verbose_name_plural': "O'quv rejalari",
                'unique_together': {('group', 'subject', 'semester')},
            },
        ),
    ]
