# Generated by Django 4.2.13 on 2026-05-11 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stipendiya',
                'verbose_name_plural': 'Stipendiyalar',
            },
        ),
        migrations.CreateModel(
            name='FinancialContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kontrakt',
                'verbose_name_plural': 'Kontraktlar',
            },
        ),
    ]
